In [1]:
from pypdf import PdfReader
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
pdf_path = "../dataset/sefat_khan.pdf"

reader = PdfReader(pdf_path)

text = ""

for page in reader.pages:
    page_text = page.extract_text()

    if page_text:
        text += page_text + "\n"

print(text[:3000])

MD. SEFAT KHAN 
Full Stack Web 
Developer  
 
 
                                    Dhaka, Bangladesh | 01308706982 | sefatkhan2231@gmail.com 
                                    Portfolio | GitHub | LinkedIn 
 
ABOUT ME 
 
 
 
Full Stack Web Developer with hands-on industry experience building responsive and scalable web 
applications using React, Laravel, and MySQL. Skilled in frontend performance optimization, REST API 
integration, authentication systems, and modern UI development. 
 
SKILLS 
 
 Languages: JavaScript, TypeScript, PHP, Python, SQL, HTML, CSS 
 Frontend: React.js, Redux Toolkit, Tailwind CSS, Bootstrap, React Bootstrap 
 Backend: Laravel, REST APIs, Authentication Systems 
 Database: MySQL, Firebase 
 Tools: Git, GitHub 
 
 Soft Skills: Time management, problem solving, teamwork, adaptability, attention to detail, 
reliability 
 
 Communication Skills: English (Intermediate), Bengali (Native) 
PROFESSIONAL EXPERIENCE  
 
Web Developer Intern — Rafusoft Softwar

In [3]:
print(type(text))
print(len(text))

<class 'str'>
2238


In [4]:
words = text.split()

chunk_size = 100

chunks = []

for i in range(0, len(words), chunk_size):
    chunk = " ".join(words[i:i + chunk_size])
    chunks.append(chunk)

print("Number of chunks:", len(chunks))

Number of chunks: 3


In [5]:
for i, chunk in enumerate(chunks):
    print(f"\n--- Chunk {i} ---")
    print(chunk[:500])


--- Chunk 0 ---
MD. SEFAT KHAN Full Stack Web Developer Dhaka, Bangladesh | 01308706982 | sefatkhan2231@gmail.com Portfolio | GitHub | LinkedIn ABOUT ME Full Stack Web Developer with hands-on industry experience building responsive and scalable web applications using React, Laravel, and MySQL. Skilled in frontend performance optimization, REST API integration, authentication systems, and modern UI development. SKILLS  Languages: JavaScript, TypeScript, PHP, Python, SQL, HTML, CSS  Frontend: React.js, Redux To

--- Chunk 1 ---
reliability  Communication Skills: English (Intermediate), Bengali (Native) PROFESSIONAL EXPERIENCE Web Developer Intern — Rafusoft Software Technologies (Nov 2025 – Feb 2026)  Developed responsive React components with Tailwind CSS during internship, contributing to 3 live client projects and improving UI consistency across devices.  Built backend modules using Laravel and MySQL, including authentication and CRUD systems  Integrated REST APIs and optimized

In [6]:
model = SentenceTransformer("all-MiniLM-L6-v2")

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

In [25]:
print(model)

SentenceTransformer(
  (0): Transformer({'transformer_task': 'feature-extraction', 'modality_config': {'text': {'method': 'forward', 'method_output_name': 'last_hidden_state'}}, 'module_output_name': 'token_embeddings', 'architecture': 'BertModel'})
  (1): Pooling({'embedding_dimension': 384, 'pooling_mode': 'mean', 'include_prompt': True})
  (2): Normalize({'module_input_name': 'sentence_embedding', 'module_output_name': 'sentence_embedding'})
)


In [7]:
sentence = "I am a Python developer with machine learning experience."

embedding = model.encode(sentence)

print(type(embedding))
print(embedding.shape)

<class 'numpy.ndarray'>
(384,)


In [8]:
sentences = [
    "I am a Python developer with machine learning experience.",
    "I develop machine learning applications using Python.",
    "I enjoy playing football and watching cricket."
]

In [9]:
embeddings = model.encode(sentences)

print(embeddings.shape)

(3, 384)


In [26]:
print(embedding[:10])

[-0.04517979  0.00622678 -0.06401033  0.02892154  0.00511879 -0.15666029
 -0.04062855  0.08096721 -0.05162472 -0.02582365]


In [10]:
similarity_01 = cosine_similarity(
    [embeddings[0]],
    [embeddings[1]]
)

similarity_02 = cosine_similarity(
    [embeddings[0]],
    [embeddings[2]]
)

print("Sentence 1 vs Sentence 2:", similarity_01[0][0])
print("Sentence 1 vs Sentence 3:", similarity_02[0][0])

Sentence 1 vs Sentence 2: 0.868976
Sentence 1 vs Sentence 3: 0.19617017


In [11]:
sentences = [
    "I am an experienced Python developer.",
    "I have professional experience developing software with Python.",
    "I am a frontend React developer.",
    "I enjoy playing football."
]

embeddings = model.encode(sentences)

for i in range(len(sentences)):
    for j in range(i + 1, len(sentences)):
        score = cosine_similarity(
            [embeddings[i]],
            [embeddings[j]]
        )[0][0]

        print(f"{i} vs {j}: {score:.4f}")
        print("  ", sentences[i])
        print("  ", sentences[j])
        print()


0 vs 1: 0.8896
   I am an experienced Python developer.
   I have professional experience developing software with Python.

0 vs 2: 0.4601
   I am an experienced Python developer.
   I am a frontend React developer.

0 vs 3: 0.0875
   I am an experienced Python developer.
   I enjoy playing football.

1 vs 2: 0.3700
   I have professional experience developing software with Python.
   I am a frontend React developer.

1 vs 3: 0.0969
   I have professional experience developing software with Python.
   I enjoy playing football.

2 vs 3: 0.0753
   I am a frontend React developer.
   I enjoy playing football.



In [12]:
sentence = "I am an experienced Python developer."

embedding = model.encode(sentence)

print(embedding)

[-4.51797880e-02  6.22677570e-03 -6.40103295e-02  2.89215390e-02
  5.11879008e-03 -1.56660289e-01 -4.06285487e-02  8.09672102e-02
 -5.16247153e-02 -2.58236453e-02 -5.51048405e-02  1.58487428e-02
  5.90018295e-02  1.43321278e-03  6.14314191e-02 -1.72112007e-02
 -8.29020888e-02 -2.67365072e-02  5.29742949e-02 -1.57166839e-01
 -7.69012002e-03  2.62394231e-02  2.47207005e-02 -2.00315323e-02
  1.71490014e-02 -8.86070207e-02  7.37951184e-03  2.27888152e-02
  7.67821744e-02 -2.74898056e-02 -4.03616987e-02  3.64133380e-02
  2.18810998e-02  2.41399743e-02  6.35252744e-02  9.65845138e-02
  1.03751328e-02 -4.34793234e-02 -3.49761993e-02  6.96430355e-03
 -2.74885795e-03 -2.74259760e-03 -7.53982365e-02 -4.82729934e-02
 -5.07785976e-02 -6.20414764e-02 -4.93183658e-02 -1.21143879e-02
  6.44843653e-02 -1.68743301e-02 -8.08065832e-02  2.84510967e-03
 -7.66418651e-02 -5.74251190e-02 -6.91390503e-03 -1.06211174e-02
  5.81169091e-02 -2.52533369e-02 -1.08270056e-03 -1.17752522e-01
  8.56072083e-03  2.57456

In [13]:
print("Dimensions:", len(embedding))

Dimensions: 384


In [14]:
sentences = [
    "Python developer",
    "Python programmer",
    "Python software engineer",
    "Machine learning engineer",
    "React frontend developer",
    "Football player"
]

In [15]:
embeddings = model.encode(sentences)

In [16]:
similarity_matrix = cosine_similarity(embeddings)

print(similarity_matrix)

[[1.         0.8872182  0.8851303  0.3918474  0.34893942 0.10636602]
 [0.8872182  1.0000001  0.8723723  0.40797198 0.24739546 0.15590815]
 [0.8851303  0.8723723  1.0000001  0.5075747  0.26399884 0.1612638 ]
 [0.3918474  0.40797198 0.5075747  1.0000001  0.23530674 0.22785997]
 [0.34893942 0.24739546 0.26399884 0.23530674 1.0000002  0.02773994]
 [0.10636602 0.15590815 0.1612638  0.22785997 0.02773994 1.        ]]


In [17]:
job_description = """
We are looking for a Machine Learning Engineer
with strong Python programming skills,
experience with NLP and Transformers,
and knowledge of SQL.
"""

In [18]:
resume_chunks = [
    "Developed machine learning models using Python and scikit-learn.",
    "Built NLP classification systems using BERT and Transformers.",
    "Developed React applications using JavaScript.",
    "Worked with MySQL and SQL databases.",
    "Played football for the university team."
]

In [19]:
job_embedding = model.encode([job_description])

chunk_embeddings = model.encode(resume_chunks)

In [20]:
scores = cosine_similarity(
    job_embedding,
    chunk_embeddings
)[0]

In [21]:
for chunk, score in zip(resume_chunks, scores):
    print(f"{score:.4f} → {chunk}")

0.4823 → Developed machine learning models using Python and scikit-learn.
0.3452 → Built NLP classification systems using BERT and Transformers.
0.0651 → Developed React applications using JavaScript.
0.2582 → Worked with MySQL and SQL databases.
0.0597 → Played football for the university team.


In [22]:
queries = [
    "Python programming experience",
    "Natural language processing and Transformers experience",
    "SQL database experience",
]

In [23]:
resume_chunks = [
    "Developed machine learning models using Python and scikit-learn.",
    "Built NLP classification systems using BERT and Transformers.",
    "Developed React applications using JavaScript.",
    "Worked with MySQL and SQL databases.",
    "Played football for the university team."
]

In [24]:
query_embeddings = model.encode(queries)
chunk_embeddings = model.encode(resume_chunks)

similarities = cosine_similarity(
    query_embeddings,
    chunk_embeddings
)

for i, query in enumerate(queries):
    print(f"\nQUERY: {query}")
    
    for j, chunk in enumerate(resume_chunks):
        print(f"{similarities[i][j]:.4f} → {chunk}")


QUERY: Python programming experience
0.4409 → Developed machine learning models using Python and scikit-learn.
0.1934 → Built NLP classification systems using BERT and Transformers.
0.1589 → Developed React applications using JavaScript.
0.0991 → Worked with MySQL and SQL databases.
0.0362 → Played football for the university team.

QUERY: Natural language processing and Transformers experience
0.2011 → Developed machine learning models using Python and scikit-learn.
0.6174 → Built NLP classification systems using BERT and Transformers.
0.1371 → Developed React applications using JavaScript.
0.0875 → Worked with MySQL and SQL databases.
-0.0196 → Played football for the university team.

QUERY: SQL database experience
0.1193 → Developed machine learning models using Python and scikit-learn.
0.0318 → Built NLP classification systems using BERT and Transformers.
0.1101 → Developed React applications using JavaScript.
0.3629 → Worked with MySQL and SQL databases.
0.0469 → Played football